# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{ ... }:
{
  programs.nvf.settings.vim.clipboard = {
    enable = true;
    providers.wl-copy.enable = true;
  };
}
