# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/home/nvf/plugins/languages.nix
{pkgs, ...}:
{
  programs.nvf.settings.vim = {
    lsp = {
      enable = true;
      formatOnSave = true;
      inlayHints.enable = true;
      lightbulb.enable = true;
    };

    languages = {
      enableTreesitter = true;
      enableFormat = true;

      nix = {
        enable = true;
        lsp.servers = ["nixd"];
      };
      lua.enable = true;
      toml.enable = true;
      rust = {
        enable = true;
        extensions.crates-nvim.enable = true;
      };
    };

    treesitter.grammars = with pkgs.vimPlugins.nvim-treesitter.grammarPlugins; [
      kdl
    ];
  };
}
