# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/home/nvf/plugins/whichkey.nix --
{ ... }:
{
  programs.nvf.settings.vim = {
    visuals.nvim-web-devicons.enable = true;

    binds.whichKey = {
      enable = true;

      register = {
        "<leader>f" = "+format/find";
        "<leader>g" = "+neogit";
        "<leader>b" = "+buffer";
        "<leader>c" = "+crates";
        "<leader>l" = "+lsp";
      };

      setupOpts = {
        expand = 5;
        preset = "modern";  # 默认是 "classic"，可选：false | "classic" | "modern" | "helix"
      };
    };
  };
}
