# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{ inputs, ... }:

{
  imports = [
    inputs.disko.nixosModules.disko
    ./disko.nix
    ../shared
    ./base.nix
    ./network.nix
    ./users.nix
    ./naiveproxy.nix
    ./dae.nix
    ./services.nix
  ];
}
