# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{ inputs, config, ... }:
{
  imports = [
    inputs.noctalia.homeModules.default
  ];

  programs.noctalia = {
    enable = true;
    systemd.enable = true;
    settings = {
      shell = {
        polkit_agent = true;
        launch_apps_as_systemd_services = true;
        greeter_sync = {
          auto_sync = true;
          privilege_command = "alacritty -e run0";
        };
      };

      wallpaper = {
        enabled = true;
        directory = "/home/kim/Pictures/Wallpapers";
      };

      location.address = "Dalian, CN";
    };
  };
}
