-- DO NOT EDIT THIS FILE DIRECTLY.
-- It is generated from flake.org by org-babel-tangle.

-- after/ftplugin/lua.lua
vim.pack.add({ "https://github.com/folke/lazydev.nvim" })

local status, lazydev = pcall(require, "lazydev")
if status then
    lazydev.setup({
        library = {
            { path = "${3rd}/luv/library", words = { "vim%.uv" } },
        },
    })
end

vim.opt_local.shiftwidth = 2
vim.opt_local.tabstop = 2
