# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{
  description = "Rust development template with Fenix";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, fenix }:
    let
      system = "x86_64-linux";
      # 在 pkgs 中引入 fenix 的 overlay
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ fenix.overlays.default ];
      };

      # 定义你想要的 Rust 工具链
      # 这里使用了 stable 版本，你也可以改为 fenix.minimal 或 fenix.nightly
      toolchain = pkgs.fenix.stable.withComponents [
        "cargo"
        "clippy"
        "rust-src"
        "rustc"
        "rustfmt"
        "rust-analyzer"
      ];
    in {
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [
          toolchain
        ];
      };
    };
}
