# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{ pkgs, ... }:

{
  programs.zed-editor = {
    enable = true;
    package = pkgs.zed-editor;
    extensions = [
      "nix"
      "toml"
      "markdown"
    ];

    # 对应 ~/.config/zed/settings.json 的声明式配置
    userSettings = {
      # --- 字体与显示大小 ---
      buffer_font_family = "JetBrainsMono Nerd Font";
      buffer_font_size = 12; # 对应你截图中的 12
      buffer_font_weight = 400;

      # ⚡ 修正 1：主编辑器的行高配置使用 "buffer_line_height"
      # 可选值有: "comfortable" (默认), "standard", 或自定义比例如 { "custom" = 1.5; }
      buffer_line_height = "comfortable";

      ui_font_family = "Inter";
      ui_font_size = 14; # 对应你截图中的 14

      # --- 终端设置 ---
      terminal = {
        font_family = "JetBrainsMono Nerd Font";
        font_size = 12;
        # 终端内的行高，这里可以使用 "line_height"
        line_height = "standard";
      };

      # --- 外观与行为 ---
      theme = "One Dark";
      icon_theme = "Zed (Default)";

      # ⚡ 修正 2：新版相对行号改用字符串 "enabled"
      relative_line_numbers = "enabled";

      indent_guides = {
        enabled = true;
        coloring = "indent_aware";
      };

      vim_mode = false;
    };
  };
}
