;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setopt user-full-name "Kim"
        user-mail-address "kimuxer@gmail.com"

        org-directory "~/.cache/emacs/org/"

        display-line-numbers-type 'visual

        doom-theme 'doom-one
        doom-font "JetBrainsMono Nerd Font:style=SemiBold:size=13"
        doom-variable-pitch-font (font-spec :family "Noto Sans CJK SC" :size 13))
;; test
;; -------------------------------------------------------------------
;;  org 基础设置（普通变量，无需等待 org 包加载，可直接顶层设置）
;; -------------------------------------------------------------------
;;(add-hook! 'org-mode-hook #'org-overview)

(setopt org-hide-leading-stars t             ; 隐藏多余的星号
        org-odd-levels-only nil              ; 保持层级清晰
        org-element-cache-persistent t
        org-src-fontify-natively t
        org-src-tab-acts-natively t
        org-element-use-cache t)

(after! org
  ;; 高度调整集中在一份数据里，方便以后新增层级或调整数值，无需重复写 set-face-attribute
  (dolist (face-height '((org-level-1        . 1.1)
                          (org-level-2        . 1.0)
                          (org-level-3        . 1.0)
                          (org-level-4        . 1.0)
                          (org-level-5        . 1.0)
                          (org-document-title . 1.1)))
    (set-face-attribute (car face-height) nil :height (cdr face-height))))

(after! org-roam
  (setopt org-roam-directory (file-truename "~/.cache/emacs/org/roam/"))
  ;; 确保目录存在，否则新机器上首次启动会因目录不存在而报错
  (make-directory org-roam-directory t)
  (org-roam-db-autosync-mode))

;; -------------------------------------------------------------------
;; Fish Shell 兼容性配置（解决 doom doctor 的 POSIX 警告）
;; -------------------------------------------------------------------
;;; add to $DOOMDIR/config.el
(setq shell-file-name (executable-find "bash"))
;;; add to $DOOMDIR/config.el
(setq-default vterm-shell "/run/current-system/sw/bin/fish")
(setq-default explicit-shell-file-name "/run/current-system/sw/bin/fish")

;; -------------------------------------------------------------------
;;  添加警告信息到生成的文件
;; -------------------------------------------------------------------

(defun +my/add-tangle-warning-h ()
  (let* ((file buffer-file-name)
         (ext (file-name-extension file)))
    (when (member ext '("nix" "sh" "kdl" "el" "lua" "yaml"))
      (let ((comment-char (cond ((string= ext "kdl") "//")
                                ((string= ext "el") ";;")
                                ((string= ext "lua") "--")
                                (t "#"))))
        (save-excursion
          (goto-char (point-min))
          (unless (search-forward "DO NOT EDIT" nil t)
            (goto-char (point-min))
            (insert (format "%s DO NOT EDIT THIS FILE DIRECTLY.\n" comment-char)
                    (format "%s It is generated from flake.org by org-babel-tangle.\n\n" comment-char))
            (save-buffer)))))))

(add-hook 'org-babel-post-tangle-hook #'+my/add-tangle-warning-h)

;; -------------------------------------------------------------------
;;  " tangle 快捷键配置"
;; -------------------------------------------------------------------

(defun +org/tangle-current-file-only ()
  (interactive)
  (unless (org-in-src-block-p)
    (user-error "光标不在代码块内"))
  (org-babel-tangle '(16))
  (message "已成功 Tangle: %s" (buffer-file-name)))

(after! org
  (map! :map org-mode-map
        :localleader
        (:prefix-map ("B" . "tangle")
         :desc "Tangle whole file" "a" #'org-babel-tangle
         :desc "Detangle current file" "d" #'org-babel-detangle
         :desc "Tangle current block's file only" "f" #'+org/tangle-current-file-only)))


;; -------------------------------------------------------------------
;; Evil 分屏后自动聚焦新窗
;; -------------------------------------------------------------------
(setopt evil-split-window-below t
        evil-vsplit-window-right t)

;; -------------------------------------------------------------------
;; 排除，`projectile`/`consult-ripgrep`/`find-file` 索引
;; -------------------------------------------------------------------
(after! projectile
  (dolist (dir '("result" "result-*" ".direnv"))
    (add-to-list 'projectile-globally-ignored-directories dir)))

;; -------------------------------------------------------------------
;; which-key 弹出延迟
;; -------------------------------------------------------------------
(setopt which-key-idle-delay 0.3)

;; -------------------------------------------------------------------
;; 备份文件位置  ~/.cache/emacs
;; -------------------------------------------------------------------
;; 原来用 (after! emacs ...) 包裹，但 Emacs 核心从不会
;; (provide 'emacs)，所以这个 after! 永远不会触发，里面的设置
;; 全部失效。这些是核心内建变量，启动早期就可用，直接去掉
;; after! 包裹、顶层执行即可
(let ((cache-dir (expand-file-name "~/.cache/emacs/")))
  (setopt backup-directory-alist `(("." . ,(expand-file-name "backups/" cache-dir)))
            auto-save-file-name-transforms `((".*" ,(expand-file-name "auto-save/" cache-dir) t))
            savehist-file (expand-file-name "history" cache-dir))
  ;; 确保目录存在
  (make-directory (cdr (car backup-directory-alist)) t)
  (make-directory (cadr (car auto-save-file-name-transforms)) t))
