# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/desktop/core.nix --
{ pkgs, ... }:
{
  # 通用系统基础能力
  security.polkit.enable = true;
  services.dbus = {
    enable = true;
    packages = [ pkgs.gsettings-desktop-schemas ];
  };
  services.gnome.gnome-keyring.enable = true;
  services.upower.enable = true;
  services.gvfs.enable = true;
  services.udisks2.enable = true;
  services.tumbler.enable = true;
  services.fwupd.enable = true;
  services.tuned.enable = true;
  services.openssh.enable = false;

  programs.dconf.enable = true;
  programs.nix-ld.enable = true;

  programs.ssh.extraConfig = ''
    Host *
      ServerAliveInterval 30
      ServerAliveCountMax 3
  '';

  programs.nh = {
    enable = true;
    flake = "/home/kim/nixos-config";
    clean = {
      enable = true;
      extraArgs = "--keep 5 --keep-since 3d";
    };
  };

  zramSwap = {
    enable = true;
    memoryPercent = 60;
  };

  programs.fish.enable = true;

  environment.systemPackages = with pkgs; [
    evtest
    udiskie
    btrfs-assistant
    btrfs-progs
    adw-gtk3
    papirus-icon-theme
    bibata-cursors
    emacs-lsp-booster
    graphviz
  ];
}
