# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/desktop/default.nix --
{ inputs, ... }:
{
  imports = [
    inputs.disko.nixosModules.disko
    ../shared
    ./disko.nix
    ./base.nix
    ./hardware.nix
    ./storage.nix
    ./hm.nix
    ./core.nix
    ./desktop.nix
    ./kanata.nix
    ./fonts.nix
    ./starship.nix
    ./ollama.nix
    #./virtualisation.nix
  ];
}
