# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/desktop/virtualisation.nix --
{ pkgs, ... }:
{
  # 1. 开启 libvirtd 虚拟化守护进程
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      package = pkgs.qemu_kvm;
      runAsRoot = true;
    };
    onBoot = "ignore";
    onShutdown = "shutdown";
  };
  systemd.services.libvirtd = {
    serviceConfig = {
      # 1. 允许服务在停止时超时，超时后直接 kill 进程，而不是死等
      TimeoutStopSec = "5s";
      # 2. 确保它在关机序列中较早被停止，避免与挂载点或网络服务冲突
      KillMode = "process";
    };
  };
  # 2. 开启 virt-manager 图形化管理客户端
  programs.virt-manager.enable = true;

  networking.firewall.trustedInterfaces = [ "virbr0" ];
  # 3. 启用 Spice USB 重定向（允许虚拟机直接读取你插在物理机上的 U 盘） [cite: 1.2.2]
  virtualisation.spiceUSBRedirection.enable = true;
}
