# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

{ config, pkgs, ... }:
{
  services.emacs.enable = true;

  programs.emacs = {
    enable = true;
    package = pkgs.emacs31-pgtk;
  };

  home.packages = with pkgs; [
    gnumake
    libtool
    clang
    cmake
    libxml2
    nixfmt
    shfmt
    nixd
    pandoc # 提供 Markdown 编译/预览支持
    shellcheck # 提供 Shell 脚本的实时语法检查
    emacs-lsp-booster
    graphviz
  ];

  xdg.configFile."doom" = {
    source = ./configs;
    recursive = true;
  };
}
