# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/home/helix/default.nix --
{
  inputs,
  config,
  osConfig,
  pkgs,
  lib,
  ...
}:
{
  programs.helix = {
    enable = true;
    defaultEditor = false;
    settings = {
      theme = "catppuccin_mocha";

      editor = {
        line-number = "relative"; # 开启相对行号
        scrolloff = 5; # 光标距离边缘剩 5 行时开始滚动
        #mouse = false; # 禁用鼠标

        cursorline = true; # 高亮当前光标所在行
        color-modes = true; # 模式切换时状态栏变色
        completion-trigger-len = 1; # 敲 1 个字母就弹出补全

        cursor-shape = {
          normal = "block";
          insert = "bar";
          select = "underline";
        };

        whitespace.render = {
          space = "none";
          tab = "all";
          newline = "none";
        };

        indent-guides = {
          render = true;
          character = "╎";
        };

        file-picker = {
          hidden = false; # 模糊搜索包含隐藏文件
          git-ignore = true; # 尊重 .gitignore
        };

        statusline = {
          left = [
            "mode"
            "spinner"
            "file-name"
            "file-modification-indicator"
          ];
          center = [ "diagnostics" ];
          right = [
            "version-control" # 显示当前 Git 分支
            "selections"
            "primary-selection-length"
            "position"
            "file-encoding"
            "file-type"
          ];
          mode = {
            normal = "NORMAL";
            insert = "INSERT";
            select = "SELECT";
          };
        };
      };
    };
  };
}
