-- DO NOT EDIT THIS FILE DIRECTLY.
-- It is generated from flake.org by org-babel-tangle.

-- lua/config/keymaps.lua

vim.keymap.set(
    "n",
    "-",
    "<CMD>lua MiniFiles.open()<CR>",
    { desc = "Open Current directory in MiniFiles" }
)

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")

-- conform
vim.keymap.set("n", "<leader>fm", function()
    require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "[M]ormat buffer" })

-- 系统剪贴板
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]], { desc = "Yank to system clipboard" })
vim.keymap.set("n", "<leader>Y", [["+Y]], { desc = "Yank line to system clipboard" })
vim.keymap.set({ "n", "v" }, "<leader>p", [["+p]], { desc = "Paste from system clipboard" })
