-- DO NOT EDIT THIS FILE DIRECTLY.
-- It is generated from flake.org by org-babel-tangle.

-- lua/config/options.lua

vim.g.mapleader = " "
vim.g.maplocalleader = " "

local wo = vim.wo
wo.relativenumber = true
wo.number = true

local opt = vim.opt
opt.swapfile = false
opt.termguicolors = true
opt.cursorline = true
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.mouse = 'a'
opt.wrap = false
opt.breakindent = true
opt.ignorecase = true
opt.smartcase = true
opt.scrolloff = 10
opt.confirm = true
opt.encoding = 'utf-8'
opt.fileencoding = 'utf-8'
opt.path:append("**")

opt.wildignore:append({
    "*/.git/*",
    "*/build/*",
    "*/dist/*",
    "*/node_modules/*",
    "*/result*",
    "*/.direnv/*",
})
