;; DO NOT EDIT THIS FILE DIRECTLY.
;; It is generated from flake.org by org-babel-tangle.

;;; early-init.el  -*- lexical-binding: t; -*-
;; =============================================================================
;; 1. 【EARLY-INIT STAGE】 Performance and GUI Optimizations
;; =============================================================================
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)

;; Prevent frame flickering on Wayland/PGTK before rendering
(setq frame-inhibit-implied-resize t)
(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)

(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))

(setq inhibit-startup-screen t
      inhibit-startup-echo-area-message t
      inhibit-startup-buffer-menu t)

;; Restore GC threshold after startup to prevent memory leaks
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq gc-cons-threshold (* 16 1024 1024)
                  gc-cons-percentage 0.1)))
