;;; emacs.el  -*- lexical-binding: t; -*-
;; =============================================================================
;; 1. 【INIT STAGE】 General Behavior and Core Settings
;; =============================================================================
(setq-default fill-column 80
              tab-width 2
              indent-tabs-mode nil)
(setq require-final-newline t)
(electric-pair-mode 1)
(show-paren-mode 1)
(delete-selection-mode 1)
(setq make-backup-files nil
      auto-save-default nil
      create-lockfiles nil)
(setq show-paren-context-when-offscreen 'child-frame)

;; Force UTF-8 environment
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)
(prefer-coding-system 'utf-8)

;; Protect history file paths for read-only Nix store environment
(make-directory "~/.local/share/emacs/" t)
(use-package savehist
  :ensure nil
  :init
  (setq savehist-file (expand-file-name "savehist" "~/.local/share/emacs/"))
  (savehist-mode 1))

(use-package recentf
  :ensure nil
  :init
  (setq recentf-save-file (expand-file-name "recentf" "~/.local/share/emacs/"))
  (recentf-mode 1)
  :config
  (setq recentf-max-saved-items 200))

(use-package saveplace
  :ensure nil
  :init
  (setq save-place-file (expand-file-name "places" "~/.local/share/emacs/"))
  (save-place-mode 1))

;; Smooth scrolling settings
(setq scroll-margin 2
      scroll-conservatively 101
      scroll-preserve-screen-position t)
(column-number-mode 1)
(setq ring-bell-function 'ignore)
(setq use-short-answers t)
(global-subword-mode 1)

(use-package vterm
  :commands vterm)

(use-package treesit-fold)

(defun +my/add-tangle-warning-h ()
  (let* ((file buffer-file-name)
         (ext (file-name-extension file)))
    (when (member ext '("nix" "sh" "kdl" "el" "lua" "yaml"))
      (let ((comment-char (cond ((string= ext "kdl") "//")
                                ((string= ext "el") ";;")
                                ((string= ext "lua") "--")
                                (t "#"))))
        (save-excursion
          (goto-char (point-min))
          (unless (search-forward "DO NOT EDIT" nil t)
            (goto-char (point-min))
            (insert (format "%s DO NOT EDIT THIS FILE DIRECTLY.\n" comment-char)
                    (format "%s It is generated from flake.org by org-babel-tangle.\n\n" comment-char))
            (save-buffer)))))))

(add-hook 'org-babel-post-tangle-hook #'+my/add-tangle-warning-h)

;; =============================================================================
;; 2. 【UI STAGE】 Appearance and Themes
;; =============================================================================
(use-package doom-themes
  :demand t
  :config
  (load-theme 'doom-one t))

(use-package doom-modeline
  :demand t
  :config
  (setq doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-buffer-encoding t)
  (doom-modeline-mode 1))

(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode t)

(use-package nerd-icons
  :demand t)

(use-package dashboard
  :demand t
  :config
  (dashboard-setup-startup-hook)
  (setq dashboard-items '((recents  . 5)
                          (bookmarks . 5)
                          (projects . 5)))

  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-icon-type 'nerd-icons)
  (setq dashboard-startup-banner 'logo)

  (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*"))))

;; =============================================================================
;; 3. 【EVIL STAGE】 Vim Keybindings and Integration
;; =============================================================================
(setq evil-want-keybinding nil)
(setq evil-want-integration t)

(use-package evil
  :demand t
  :config
  (setq evil-default-state 'normal)
  (setq evil-normal-state-cursor 'box)
  (setq evil-insert-state-cursor 'bar)
  (setq evil-emacs-state-cursor 'hbar)
  (setq evil-want-clipboard-init nil)
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :demand t
  :config
  (evil-collection-init))

;; =============================================================================
;; 4. Completion UI Framework (Vertico)
;; =============================================================================
(use-package vertico
  :init
  (vertico-mode 1))

(use-package corfu
  :demand t
  :config
  (global-corfu-mode 1)
  (setq corfu-auto t
        corfu-cycle t)
  ;; Allow space to act as a separator for Orderless completion within Corfu
  (setq corfu-quit-at-boundary 'separator))

(use-package orderless
  :demand t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles basic partial-completion))))
  :config
  ;; Enable Corfu in minibuffer when completion-at-point is available
  (defun my/corfu-enable-in-minibuffer ()
    (when (local-variable-p 'completion-at-point-functions)
      (setq-local corfu-auto nil)
      (corfu-mode 1)))
  (add-hook 'minibuffer-setup-hook #'my/corfu-enable-in-minibuffer))

(use-package marginalia
  :init
  (marginalia-mode 1))

;; =============================================================================
;; 5. Syntax Highlighting (Tree-sitter)
;; =============================================================================
(setq major-mode-remap-alist
      '((rust-mode . rust-ts-mode)
        (bash-mode . bash-ts-mode)
        (json-mode . json-ts-mode)
        (lua-mode . lua-ts-mode)
        (yaml-mode . yaml-ts-mode)))

(defun my/treesit-common-setup ()
  "Common setup applied to every tree-sitter major mode."
  (treesit-inspect-mode -1)
  (treesit-fold-mode 1)
  (local-set-key (kbd "C-c C-f") 'treesit-fold-toggle))

(dolist (mode-pair major-mode-remap-alist)
  (let* ((ts-mode (cdr mode-pair))
         (ts-hook (intern (concat (symbol-name ts-mode) "-hook"))))
    (add-hook ts-hook #'my/treesit-common-setup)))

;; =============================================================================
;; 6. LSP Code Intelligence (Eglot)
;; =============================================================================
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs '(nix-mode . ("nixd")))
  (add-to-list 'eglot-server-programs '(conf-toml-mode . ("taplo" "lsp" "stdio")))
  (add-to-list 'eglot-server-programs '(bash-ts-mode . ("bash-language-server" "start"))))

(add-hook 'rust-ts-mode-hook #'eglot-ensure)
(add-hook 'bash-ts-mode-hook #'eglot-ensure)
(add-hook 'conf-toml-mode-hook #'eglot-ensure)
(add-hook 'emacs-lisp-mode-hook #'flymake-mode)

(use-package nix-mode
  :mode "\\.nix\\'"
  :hook (nix-mode . eglot-ensure))

(use-package kdl-mode
  :mode "\\.kdl\\'")

(use-package envrc
  :hook (after-init . envrc-global-mode))
(use-package inheritenv)

;; =============================================================================
;; 7. Formatting & Linting
;; =============================================================================
(use-package apheleia
  :demand t
  :config
  (apheleia-global-mode +1)

  (setf (alist-get 'nix-mode apheleia-formatters) '("alejandra" "-q"))
  (setf (alist-get 'shfmt apheleia-formatters) '("shfmt" "-i" "2" "-bn"))

  ;; 改这里: apheleia-mode-formatter-alist -> apheleia-mode-alist
  (setf (alist-get 'nix-mode apheleia-mode-alist) 'nix-mode)

;; =============================================================================
;; 8. 【MAGIT】 Magit and Project Integration
;; =============================================================================
(use-package magit
  :config
  ;; Refine all hunks for crystal clear diffs
  (setq magit-diff-refine-hunk 'all)
  ;; Prevent annoying prompts when killing Emacs with active repo buffers
  (setq magit-save-repository-buffers 'dontask)
  ;; Control buffer display behavior to keep workspace clean
  (setq magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

;; Integrate Magit seamlessly into project.el switch menu
(with-eval-after-load 'project
  (add-to-list 'project-switch-commands '(magit-status "Magit status") t))

;; =============================================================================
;; 9. 【ORG】 Org Mode Configuration
;; =============================================================================4
(use-package org
  :ensure nil
  :config
  (setq org-hide-emphasis-markers t)
  (add-hook 'org-mode-hook #'visual-line-mode)
  (setq org-return-follows-link t)

  (use-package org-appear
    :hook (org-mode . org-appear-mode)))

(with-eval-after-load 'org
  (setq org-directory "~/org")
  (setq org-agenda-files (list org-directory))
  (setq org-todo-keywords
        '((sequence "TODO(t)" "PROG(p)" "|" "DONE(d)" "CANCELLED(c)")))
  (setq org-log-done 'time))

;; =============================================================================
;; 10. 【KEYBINDINGS】 Keybindings (Modern Leader Key Setup)
;; =============================================================================
(use-package consult)

(use-package which-key
  :init (which-key-mode 1)
  :config
  (setq which-key-idle-delay 0.3))

(use-package general
  :demand t
  :config
  (general-evil-setup)

  (eval-and-compile
    (general-create-definer my-leader-def
      :states '(normal visual motion)
      :keymaps 'override
      :prefix "SPC"
      :global-prefix "C-SPC"))

  (general-define-key
   :states 'normal
   "C-p" 'project-find-file)

  ;; 3. SPC Leader Key Map
  (my-leader-def
    ;; Top-level single-letter binds
    "SPC" '(execute-extended-command :which-key "M-x")
    "/"   '(consult-line :which-key "Search buffer")

    ;; [b] Buffers (Fixed: Removed void keymap variable)
    "b"   '(:which-key "buffers")
    "bb"  '(switch-to-buffer :which-key "Switch buffer")
    "bd"  '(kill-current-buffer :which-key "Kill buffer")
    "bn"  '(next-buffer :which-key "Next buffer")
    "bp"  '(previous-buffer :which-key "Previous buffer")

    ;; [c] Code / LSP (Integration with Eglot from Part C)
    "c"   '(:which-key "code/lsp")
    "ca"  '(eglot-code-actions :which-key "Code actions")
    "cr"  '(eglot-rename :which-key "Rename symbol")
    "cf"  '(apheleia-format-buffer :which-key "Format buffer") ; Force Apheleia
    "cd"  '(eldoc :which-key "Show docs")

    ;; [f] Files
    "f"   '(:which-key "files")
    "ff"  '(find-file :which-key "Find file")
    "fr"  '(recentf-open-files :which-key "Recent files")

    ;; [g] Git (Integration with Magit)
    "g"   '(:which-key "git")
    "gg"  '(magit-status :which-key "Magit status")

    ;; [t] Toggle / Terminal (Integration with Vterm)
    "t"   '(:which-key "toggle/terminal")
    "tt"  '(vterm :which-key "Open Vterm")

    ;; [o] Org Mode (Integration with Org Mode from Part B)
    "o"   '(:which-key "org")
    "oa"  '(org-agenda :which-key "Agenda")
    "ot"  '(org-capture :which-key "Capture")))
