;; DO NOT EDIT THIS FILE DIRECTLY.
;; It is generated from flake.org by org-babel-tangle.

;;; === FILE: modules/home/emacs/configs/lisp/core-evil.el ===
;;; core-evil.el --- Vim 模式配置 -*- lexical-binding: t; -*-

;; 1. evil 依赖的前置变量
(setq evil-want-keybinding nil)
(setq evil-want-integration t)

;; 2. 加载并配置 evil
(use-package evil
  :demand t
  :config
  (setq evil-default-state 'normal)
  (setq evil-normal-state-cursor 'box)
  (setq evil-insert-state-cursor 'bar)
  (setq evil-emacs-state-cursor 'hbar)
  ;; --- 核心修改点：保持独立剪切板 ---
  (setq evil-want-clipboard-init nil)
  (evil-mode 1))

;; 3. evil-collection：保持原有的 dired/magit 等模式的 vim 化
(use-package evil-collection
  :after evil
  :demand t
  :config
  (evil-collection-init))

;; 4. 剪切板分离功能函数 (留在这里，供 core-keybindings 调用)
(defun my/copy-to-system-clipboard (beg end)
  (interactive "r")
  (gui-set-selection 'CLIPBOARD (buffer-substring-no-properties beg end)))

(defun my/copy-line-to-system-clipboard ()
  (interactive)
  (gui-set-selection 'CLIPBOARD (buffer-substring-no-properties
                                 (line-beginning-position)
                                 (line-end-position))))

(defun my/paste-from-system-clipboard ()
  (interactive)
  (insert (gui-get-selection 'CLIPBOARD)))

(provide 'core-evil)
;;; core-evil.el ends here
