;; DO NOT EDIT THIS FILE DIRECTLY.
;; It is generated from flake.org by org-babel-tangle.

;;; === FILE: modules/home/emacs/configs/lisp/core-keybindings.el ===
;;; core-keybind.el --- 全局按键绑定 -*- lexical-binding: t; -*-

;; 放在 my-core-modules 列表最后加载，是因为这里大量用到
;; evil-define-key，必须保证 evil 已经真正加载完（core-evil.el
;; 里 evil 是 :demand t，所以到这里时 evil 肯定已经可用）。
;;
;; 注意：你目前没有装 general.el，所以这里不用 general-define-key
;; 那套写法，改用 evil 自带的 evil-define-key，效果类似（定义一个
;; 以 SPC 开头的"leader key"），只是没有 general.el 那么多语法糖。
;; 如果以后觉得 leader key 定义多了、想要更好维护，可以考虑把
;; general.el 加进 home.nix，再回来重构这个文件。

;; magit 的具体配置（:bind 之类）已经拆到 core-magit.el 里了，
;; 这里的 leader key 直接引用 #'magit-status 这个符号即可，
;; 不需要关心它是在哪个文件里被加载/绑定的。

;; === 1. Leader key（SPC）===
;; 只在 normal / visual / motion 状态下生效，插入模式不受影响。
;; 挂在 'global 上，意味着这套绑定在所有 buffer 里默认可用，
;; 除非某个 major mode 自己在同一前缀下定义了更高优先级的绑定。

(evil-define-key '(normal visual motion) 'global
  ;; -- 文件 --
  (kbd "SPC f f") #'find-file
  (kbd "SPC f s") #'save-buffer
  (kbd "SPC f r") #'recentf-open

  ;; -- buffer --
  (kbd "SPC b b") #'switch-to-buffer
  (kbd "SPC b k") #'kill-current-buffer
  (kbd "SPC b n") #'next-buffer
  (kbd "SPC b p") #'previous-buffer

  ;; -- 窗口 --
  (kbd "SPC w s") #'split-window-below
  (kbd "SPC w v") #'split-window-right
  (kbd "SPC w d") #'delete-window
  (kbd "SPC w o") #'delete-other-windows

  ;; -- 剪切板操作 (Vim 风格分离) --
  (kbd "SPC y") #'my/copy-to-system-clipboard
  (kbd "SPC Y") #'my/copy-line-to-system-clipboard
  (kbd "SPC p") #'my/paste-from-system-clipboard

  ;; -- Git / Magit --
  (kbd "SPC g s") #'magit-status

  ;; -- LSP / Formatting --
  (kbd "SPC c a") #'eglot-code-actions
  (kbd "SPC c r") #'eglot-rename
  (kbd "SPC c f") #'apheleia-format-buffer

  ;; -- Project（注意：用大写 P，不能用小写 p）--
  ;; 上面 "SPC p" 已经绑定成了具体命令 my/paste-from-system-clipboard，
  ;; 而不是一个前缀 keymap。如果这里再定义 "SPC p f" / "SPC p p"，
  ;; define-key 会把 "SPC p" 从"命令"悄悄改造成"前缀 keymap"，
  ;; 结果是 SPC p 粘贴功能被顶掉、且没有任何报错提示，非常隐蔽。
  ;; 这也是之前这三行被注释掉、一直没启用的真正原因。
  ;; 解决办法很简单：project 前缀换成没被占用的大写 "SPC P" 即可。
  (kbd "SPC P f") #'project-find-file
  (kbd "SPC P p") #'project-switch-project
  (kbd "SPC P b") #'project-switch-to-buffer

  ;; -- 杂项 --
  (kbd "SPC SPC") #'execute-extended-command
  (kbd "SPC q q") #'save-buffers-kill-terminal)

;; === 3. 少量非 leader 的直接绑定 ===
(global-set-key (kbd "M-o") #'other-window)
(global-set-key (kbd "C-c c") #'compile)

(provide 'core-keybindings)

;;; core-keybindings.el ends here
