;; DO NOT EDIT THIS FILE DIRECTLY.
;; It is generated from flake.org by org-babel-tangle.

;;; === FILE: modules/home/emacs/configs/lisp/core-editor.el ===
;;; core-editor.el --- 通用编辑体验配置 -*- lexical-binding: t; -*-

;; 这个文件只放"跟具体某个第三方包无关、Emacs 内置就有"的编辑体验设置。
;; 需要额外插件的功能（比如 LSP、代码片段）先不写在这里，等你在
;; home.nix 里声明了对应包之后再加，避免出现"配置了但包没装"的坑
;; （这类坑之前在 core-completion.el / core-evil.el 里已经踩过了）。

;; === 1. 基础编辑行为 ===
(setq-default indent-tabs-mode nil   ; 用空格缩进，不用 tab 字符
              tab-width 2)
(setq require-final-newline t)       ; 保存时确保文件末尾有换行符
(delete-selection-mode 1)            ; 选中文字后直接输入会替换选区内容（更符合大部分编辑器直觉）
(electric-pair-mode 1)               ; 自动补全括号/引号
(show-paren-mode 1)                  ; 高亮匹配的括号
(setq show-paren-context-when-offscreen 'child-frame) ; 括号在屏幕外时用小窗口提示上下文（Emacs 29+）

;; === 2. 编码 ===
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)
(prefer-coding-system 'utf-8)

;; === 3. 历史与状态持久化 ===
;; savehist：记住 minibuffer 输入历史（配合 vertico 用起来体验会好很多，
;; 比如重复用过的搜索词、执行过的命令，下次能直接从历史里选）
(use-package savehist
  :init (savehist-mode 1))

;; recentf：记录最近打开过的文件，方便快速重新打开
(use-package recentf
  :init (recentf-mode 1)
  :config
  (setq recentf-max-saved-items 200))

;; 记住每个文件上次编辑的光标位置，重新打开时自动跳回去
(use-package saveplace
  :init (save-place-mode 1))

;; === 4. 滚动与显示 ===
(setq scroll-margin 2
      scroll-conservatively 101      ; 光标接近边缘时逐行滚动，不整屏跳动
      scroll-preserve-screen-position t)
(setq-default fill-column 80)
(column-number-mode 1)               ; 在 mode-line 显示光标所在列号（doom-modeline 也会显示，这里是兜底）

;; === 5. 减少干扰性弹窗/提示 ===
(setq ring-bell-function 'ignore)    ; 关掉响铃/闪屏
(setq use-short-answers t)           ; y/n 代替 yes/no（Emacs 28+）
(fset 'yes-or-no-p 'y-or-n-p)        ; 兼容 Emacs 28 以下版本的写法，28+ 有 use-short-answers 其实这行可以不要，留着兼容更保险

;; === 6. 括号/子词导航 ===
;; 在 camelCase / snake_case 里按词移动时，只移动到子词边界，
;; 而不是整个 camelCaseWord 一次跳过去，写代码时更常用
(global-subword-mode 1)

;; === 7. which-key ===
;; Emacs 30 开始内置，不需要在 home.nix 里额外声明包。
;; 效果：按下一个前缀键（比如 core-keybindings.el 里定义的 SPC 系列）
;; 之后停顿一下，minibuffer 会自动弹出后续可按键位的提示菜单，
;; 尤其适合你现在这套自己手写的 leader key 绑定，不用死记硬背。
(use-package which-key
  :init (which-key-mode 1)
  :config
  (setq which-key-idle-delay 0.5))    ; 停顿多久（秒）后弹出提示，嫌太快/太慢自行调整

(provide 'core-editor)
;;; core-editor.el ends here
