;; DO NOT EDIT THIS FILE DIRECTLY.
;; It is generated from flake.org by org-babel-tangle.

;;; === FILE: modules/home/emacs/configs/lisp/core-formatting.el ===
;;; core-formatting.el --- 格式化自动化配置 -*- lexical-binding: t; -*-

;; 同 core-completion.el 里 corfu 的道理：不写 :ensure t，
;; 包是 Nix 提供的，package.el 未初始化，:ensure t 在这里没有意义
;; 甚至可能报错。
(use-package apheleia
  :demand t
  :config
  ;; 1. 开启全局模式
  (apheleia-global-mode +1)

  ;; 2. 自定义格式化程序映射
  ;; Apheleia 内置了大多数工具的配置，不需要写完整的执行路径
  ;; 如果你想调整参数，直接覆盖 alist-get 即可
  (setf (alist-get 'nix-mode apheleia-formatters) '("alejandra" "-q"))
  (setf (alist-get 'sh-mode apheleia-formatters) '("shfmt" "-i" "2" "-bn"))

  ;; 3. 如果需要对某些语言自定义特定参数
  ;; (setf (alist-get 'rust-mode apheleia-formatters) '("rustfmt" "--edition" "2021"))
  )

(provide 'core-formatting)
;;; core-formatting.el ends here
