# -- modules/home/neovim/default.nix --
{ inputs, pkgs, ... }:
{
  imports = [
    inputs.nvf.homeManagerModules.default
    ./ui/ui.nix
    ./editor/options.nix
    ./editor/binds.nix
    ./plugins/whichkey.nix
    ./plugins/others.nix
    ./plugins/telescope.nix
    ./plugins/treesitter.nix
    ./plugins/formatting.nix
    ./plugins/completion.nix
    ./plugins/languages.nix
  ];

  programs.nvf = {
    enable = true;
    settings.vim = {
      viAlias = true;
      vimAlias = true;
      withNodeJs = true;
      withPython3 = true;

      globals = {
        mapleader = " ";
        maplocalleader = " ";
      };
      extraPackages = with pkgs; [
        prettierd
        yamlfmt
        tree-sitter
        rustfmt
        
      ];
    };
  };
  
  # 修复 checkhealth 检查的警告
  home.file.".config/nvf/init.lua".text = ''
    -- Generated by Nix for nvf health check satisfaction
  '';
}
