# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from flake.org by org-babel-tangle.

# -- modules/home/neovim/default.nix --
{
  inputs,
  pkgs,
  ...
}:
{
  imports = [
    inputs.nvf.homeManagerModules.default
    ./ui/ui2.nix
    ./editor/options.nix
    ./editor/binds.nix
    ./plugins/whichkey.nix
    ./plugins/telescope.nix
    ./plugins/formatting.nix
    ./plugins/completion.nix
    ./plugins/languages.nix
    ./plugins/direnv.nix
    ./plugins/clipboard.nix
    ./plugins/diagnostics.nix
    ./plugins/git.nix
  ];

  programs.nvf = {
    enable = true;
    settings.vim = {
      viAlias = true;
      vimAlias = true;
      withNodeJs = true;
      withPython3 = true;

      globals = {
        mapleader = " ";
        maplocalleader = " ";
      };

      extraPackages = with pkgs; [
        prettierd
        tree-sitter
        rustfmt
        alejandra
        stylua
        kdlfmt
        taplo
        #rust-analyzer
      ];

      luaConfigPre = ''
        -- 强行堵上 nvf 底层硬编码造成的 default_on_attach 幽灵函数漏洞
            _G.default_on_attach = function(client, bufnr)
            -- 留空让它安全通过
          end
          -- 原生替代 project.nvim 的功能
          vim.api.nvim_create_autocmd("BufEnter", {
            callback = function()
              -- 只有当还没有切换过且检测到项目根目录时才执行
              local root = vim.fs.root(0, {".git", ".root", "flake.nix", "Cargo.toml"})
              if root and vim.fn.getcwd() ~= root then
                vim.schedule(function()
                  vim.cmd("cd " .. root)
                  print("Project root switched to: " .. root)
                end)
              end
            end,
          })
      '';
    };
  };

  # 修复 checkhealth 检查的警告
  home.file.".config/nvf/init.lua".text = ''
    -- Generated by Nix for nvf health check satisfaction
  '';
}
