-- DO NOT EDIT THIS FILE DIRECTLY.
-- It is generated from flake.org by org-babel-tangle.

-- modules/home/neovim/nvim/plugin/07-direnv.lua

vim.pack.add({
    "https://github.com/DrKJeff16/project.nvim",
    "https://github.com/NotAShelf/direnv.nvim",
})

require("project").setup({
    patterns = { ".git", ".envrc", "flake.nix" }, -- 加上 .envrc，纯 direnv 项目（没有 .git）也能识别
    scope_chdir = "win",                          -- 每个窗口独立 cwd，避免分屏多项目互相干扰
    silent_chdir = true,
})

require("direnv").setup({
    -- 核心功能：进入目录时自动加载
    autoload_direnv = true,

    -- 状态栏图标
    statusline = {
        enabled = true,
        icon = "󱚟",
    },

    -- 快捷键设置
    keybindings = {
        allow = "<Leader>da",
        deny = "<Leader>dd",
        reload = "<Leader>dr",
        edit = "<Leader>de",
    },

    -- 通知设置
    notifications = {
        level = vim.log.levels.INFO,
        silent_autoload = true, -- 设置为 true 避免每次进入目录都弹出通知
    },
})
