-- DO NOT EDIT THIS FILE DIRECTLY.
-- It is generated from flake.org by org-babel-tangle.

-- modules/home/neovim/nvim/plugin/08-whichkey.lua

vim.pack.add({ "https://github.com/folke/which-key.nvim" })

require("which-key").setup({})
